[project]
name = "ucv-lab1-si"
version = "0.1.0"
description = "Proyecto de Sistemas Inteligentes"
authors = [
    {name = "moisescg18",email = "mcamonesgo@ucvvirtual.edu.pe"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=3.0.5,<4.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "jupyter (>=1.1.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
[tool.pytest.ini_options]
pythonpath = ["src"]